project:
  type: website
  output-dir: docs
website:
  title: "Amanda Cavanaugh, Designer"
  navbar:
    right:
      - index.qmd
      - blog.qmd
      - resume.qmd
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

